MotorInsurance/Areas/India/Controllers/DetailsController.cs
namespace MotorInsurance.Areas.India.Controllers
{
    using MotorInsurance.Areas.India.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class DetailsController : Controller
    {
        // GET: India/Details
        public ActionResult PersonDetails()
        {
            
            var personModel = (Person)Session["person"];
            if (personModel == null)
            {
                personModel = new Person();
            }
            return View(personModel);
        }

        public ActionResult VehicleDetails(Person personModel)
        {
            if (personModel != null && personModel.Email != null)
            {
                Session["person"] = personModel;
            }
            var vehicleModel = Session["vehicle"];
            if (vehicleModel == null)
            {
                vehicleModel = new Vehicle();
            }
            return View(vehicleModel);
        }

    }
}

MotorInsurance/Areas/UK/Controllers/DetailsController.cs
namespace MotorInsurance.Areas.UK.Controllers
{
    using JSONParser.Models;
    using MotorInsurance.Areas.UK.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class DetailsController : Controller
    {
        // GET: UK/Details
        public ActionResult PersonDetails()
        {
            var personModel = (Person)Session["person"];
            if (personModel == null)
            {
                personModel = new Person();
            }
            return View(personModel);
        }

        public ActionResult VehicleDetails(Person personModel)
        {
            if (personModel != null && personModel.Email != null)
            {
                Session["person"] = personModel;
            }
            var vehicleModel = Session["vehicle"];
            if (vehicleModel == null)
            {
                vehicleModel = new Vehicle();
            }
            return View(vehicleModel);
        }

        public ActionResult GetAddress(string postCode)
        {
            PostCode model = new PostCode();
            return PartialView(model);
        }

    }
}

MotorInsurance/Areas/UK/Controllers/EstimateController.cs
namespace MotorInsurance.Areas.UK.Controllers
{
    using GetEstimates;
    using MotorInsurance.Areas.UK.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class EstimateController : Controller
    {
        private IEstimateMethod _Estimate;

        public EstimateController(IEstimateMethod estimateMethod)
        {
            _Estimate = estimateMethod;
        }


        // GET: UK/Estimate
        public ActionResult GetEstimate(Vehicle vehicleModel)
        {
            if (vehicleModel != null)
            {
                Session["vehicle"] = vehicleModel;
            }
            Models.Estimate model = (Models.Estimate)_Estimate.GetEstimates(vehicleModel.BuildYear);

            if (model != null)
            {
                Session["quote"] = model;
                return View(model);
               
            }
            return RedirectToAction("VehicleDetails", "Details", vehicleModel);

        }
    }
}

MotorInsurance/Areas/India/Views/Details/PersonDetails.cshtml
@model MotorInsurance.Areas.India.Models.Person

@{
    ViewBag.Title = "PersonDetails";
    Layout = "~/Areas/India/Views/Shared/_IndiaLayout.cshtml";
}
<h2>PersonDetails</h2>

@using (Html.BeginForm("VehicleDetails", "Details"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control", onkeyup = "checkInputForIndia()", id = "PostCode" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"  id="AddressDiv"  style="visibility:hidden">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Address, new SelectList(string.Empty, "Value", "Text"), "---Select---", new { htmlAttributes = new { @class = "form-control", onkeyup = "checkInput()", id = "Address" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MotorInsurance/Areas/India/Views/Details/VehicleDetails.cshtml
@model MotorInsurance.Areas.India.Models.Vehicle

@{
    ViewBag.Title = "VehicleDetails";
    Layout = "~/Areas/India/Views/Shared/_IndiaLayout.cshtml";
}

<h2>VehicleDetails</h2>

@using (Html.BeginForm("GetEstimate", "Estimate"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VehicleNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EngineNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngineNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KmsTravelled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KmsTravelled, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KmsTravelled, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuildYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuildYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuildYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
                <button class="btn btn-default">@Html.ActionLink("Back", "PersonDetails")</button>
            </div>

        </div>
    </div>
}